name: Build

# Controls when the workflows will run
on:
  # Allows you to run this workflows manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch_path:
        description: 'branch'
        required: true
        default: '开发分支'
      setup_path:
        description: 'setup.py所在目录'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        git clone -b ${{ github.event.inputs.branch_path }} 'https://github.com/QPT-Family/QPT-SDK'
        cd 'QPT-SDK/'${{ github.event.inputs.setup_path }}
        python -m pip install --upgrade pip
        pip install build
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
